font_size 31.0
visual_bell_duration 0.0
bell_on_tab "🔔 "

map alt+1 switch_to_tab 0
map alt+2 switch_to_tab 1
map alt+3 switch_to_tab 2
map alt+4 switch_to_tab 3
map alt+5 switch_to_tab 4
map alt+6 switch_to_tab 5
map alt+7 switch_to_tab 6
map alt+8 switch_to_tab 7
map alt+9 switch_to_tab 8


