font_size 14.0
visual_bell_duration 0.0
bell_on_tab "🔔 "
font_family      JetBrainsMono Nerd Font
set weight as medium
font_weight      medium

background #ffffff
foreground #000000
cursor #bbbbbb
selection_background #ececec
color0 #000000
color8 #000000
color1 #de3d35
color9 #de3d35
color2 #3e953a
color10 #3e953a
color3 #d2b67b
color11 #d2b67b
color4 #2f5af3
color12 #2f5af3
color5 #950095
color13 #a00095
color6 #3e953a
color14 #3e953a
color7 #bbbbbb
color15 #ffffff
selection_foreground #f8f8f8

map alt+1 goto_tab 0
map alt+2 goto_tab 1
map alt+3 goto_tab 2
map alt+4 goto_tab 3
map alt+5 goto_tab 4
map alt+6 goto_tab 5
map alt+7 goto_tab 6
map alt+8 goto_tab 7
map alt+9 goto_tab 8




# BEGIN_KITTY_FONTS
font_family      family="Meslo LG S" 
font_bold        family="Meslo LG S" 
