#!/bin/bash
export DISPLAY=:0  # Se precisar de acesso ao display gráfico

# Run pacman -Qu and store the output in a variable
pacman_output=$(paru -Syu --noconfirm)

# Check if the output is not empty
if [ -n "$pacman_output" ]; then
  DISPLAY=:0 notify-send "Updating packages from Paru"
fi

flatpak update -y

