#!/bin/bash

# Verifica se /mnt/Documents está montado
if mountpoint -q /mnt/Documents; then
    # Desmonta o sistema de arquivos
    umount /mnt/Documents
    echo "Desmontado /mnt/Documents com sucesso."
else
    echo "/mnt/Documents não está atualmente montado."
    # Check if disks are connected
    if [ $(lsblk -o NAME | grep -c sdc) -eq 1 ]; then
        # Mount the filesystem
        mount /dev/sdc1 /mnt/Documents
        echo "Montado /mnt/Documents com sucesso."
    else
        echo "Disco não conectado."

fi


