lastupdatecheck: 0
recentrepos:
    - /home/neimog/Documents/Git/dotfiles
    - /home/neimog/Documents/Git/charlesneimog.github.io
    - /home/neimog/Documents/Git/NewPiece
    - /home/neimog/Documents/Git/pd-xlab
    - /home/neimog/Documents/Git/pd-bhack
    - /home/neimog/Documents/Git/pd-saf
    - /home/neimog/Documents/Git/Depois-de-Ser-Modelo
    - /home/neimog/Documents/Git/pd-else
    - /home/neimog/Documents/Git/SmartFit
    - /home/neimog/Documents/Git/pd4web
    - /home/neimog/Documents/Git/sonologia
    - /home/neimog/Documents/Git/pd-upic
    - /home/neimog/Documents/Git/journal
    - /home/neimog/Documents/Git/OpenScofo
    - /home/neimog/Documents/Git/PocketReader
    - /home/neimog/Documents/Git/Awesome-Pd
    - /home/neimog/Documents/Git/loris
    - /home/neimog/Documents/Git/pd.cmake
    - /home/neimog/Documents/Git/p2p
    - /home/neimog/Documents/Git/pure-data
    - /home/neimog/Downloads/pure-data
    - /home/neimog/Documents/Git/percepcao
    - /home/neimog/Documents/Git/PocketReader/thirdparty/foliate-js
    - /home/neimog/Documents/Git/pd-dddd
    - /home/neimog/Documents/Git/anytype-client
    - /home/neimog/Documents/Git/maps
    - /home/neimog/Documents/Git/web-whisper
    - /home/neimog/Documents/Git/py4pd
    - /home/neimog/Documents/Git/libonnx
    - /home/neimog/Documents/Git/pd-stk
    - /home/neimog/Documents/Git/sf-midi-player
    - /home/neimog/Documents/Git/typst-vortex-journal-template
    - /home/neimog/.local/share/nvim/site/pack/core/opt/OpenScofo
    - /home/neimog/Documents/Git/dragonfly_tilde
    - /home/neimog/Documents/Git/pd-soundtouch
    - /home/neimog/Documents/Git/concentrate
    - /home/neimog/Documents/Git/Caminhada
    - /home/neimog/Documents/Git/pd-lua
    - /home/neimog/Documents/Git/telematico
    - /home/neimog/Documents/Git/Score-follower
    - /home/neimog/Documents/Git/pd-onnx
    - /home/neimog/Documents/Git/pd-orchidea
    - /home/neimog/Documents/Git/pv~
    - /home/neimog/Documents/Git/gaiasense
startuppopupversion: 5
didshowhunkstaginghint: true
lastversion: 0.65.1
customcommandshistory:
    - q
    - ""
    - q!
    - minor updates related with py4pd changes
    - 'commit '
    - fix the pd.print for multiple args
    - '?'
hidecommandlog: false
