lastupdatecheck: 0
recentrepos:
    - /home/neimog/Documents/Git/py4pd
    - /home/neimog/Documents/Git/py4pd-upic
    - /home/neimog/Documents/Git/Espelhos-Técnicos
    - /home/neimog/Documents/Git/py4pd-orchidea
    - /home/neimog/Documents/Git/py4pd-freesound
    - /home/neimog/Documents/Git/pd4web
    - /home/neimog/Documents/Git/pd-ambi
    - /home/neimog/Documents/Git/loris
    - /home/neimog/Documents/Git/dotfiles
    - /home/neimog/Documents/Git/Cartilha
    - /home/neimog/Documents/Git/pd4web/Sources/Libraries/pd.cmake
    - /home/neimog/Documents/Git/pd-partialtrack
    - /home/neimog/Documents/Git/pd-partialtrack/Resources/pd.cmake
    - /home/neimog/Documents/Git/Thesis
    - /home/neimog/Documents/Git/OScofo
    - /home/neimog/Documents/Git/pd-partialtrack/Libraries/simpl
    - /home/neimog/Documents/Git/pd-partialtrack/Resources/CMakeAudioHelpers
    - /home/neimog/Documents/Git/Docs/Tese
    - /home/neimog/Documents/Git/pd.cmake
    - /home/neimog/Documents/Git/OScofo/Resources/pd.cmake
    - /home/neimog/Documents/Git/Caravana
    - /home/neimog/Documents/Git/py4pd/Resources/pd.cmake
    - /home/neimog/Documents/Git/pd-vamp
    - /home/neimog/Documents/Git/pd-vamp/Libraries/rt-vamp-plugin-sdk
    - /home/neimog/Documents/Git/Docs/Tese/Projects/pd-partialtrack
    - /home/neimog/Documents/Git/nucleomusicanova.github.io
    - /home/neimog/Documents/Git/charlesneimog.github.io
    - /home/neimog/Documents/Git/pd-neimog
    - /home/neimog/Documents/Git/pd-pt
startuppopupversion: 5
lastversion: 0.44.1
customcommandshistory:
    - q!
    - ""
    - q
    - minor updates related with py4pd changes
    - 'commit '
    - fix the pd.print for multiple args
    - '?'
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
