name: Python application

on:
  #schedule:
    #- cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install -r ./Scripts/requirements.txt

    - name: Reminders
      run: |
        python ./Scripts/remember-me-Updated.py --piecesDatabase ${{ secrets.PIECESDATABASE }} --emailPass ${{ secrets.EMAILPASS }} --emailSender ${{ secrets.EMAILSENDER }} --emailReceiver ${{ secrets.EMAILRECEIVER }} --notionToken ${{ secrets.NOTIONTOKEN }} --mainDataBase ${{ secrets.MAINDATABASE }} 
    
    - name: Routine
      run: | 
        python ./Scripts/update-notion-icons.py --notionToken ${{ secrets.NOTIONTOKEN }} --mainDataBase ${{ secrets.MAINDATABASE }} 
        python ./Scripts/todo-days.py --notionToken ${{ secrets.NOTIONTOKEN }} --TodoBase ${{ secrets.TODOBASE }} 
        python ./Scripts/TelegramBot.py --emailPass ${{ secrets.EMAILPASS }} --emailSender ${{ secrets.EMAILSENDER }} --emailReceiver ${{ secrets.EMAILRECEIVER }} --notionToken ${{ secrets.NOTIONTOKEN }} --telegramToken ${{ secrets.TELEGRAMTOKEN }} --dailyBase ${{ secrets.DAILYBASE }}

    - name: Articles
      run: | 
        python ./Scripts/pdf2notion.py --emailPass ${{ secrets.EMAILPASS }} --emailSender ${{ secrets.EMAILSENDER }} --emailReceiver ${{ secrets.EMAILRECEIVER }} --notionToken ${{ secrets.NOTIONTOKEN }} --mainDataBase ${{ secrets.MAINDATABASE }}
        rm -rf ./Scripts/attachments/*

    - name: Books
      run: | 
        python ./Scripts/GoogleBooks2Notion.py --emailPass ${{ secrets.EMAILPASS }} --emailSender ${{ secrets.EMAILSENDER }} --emailReceiver ${{ secrets.EMAILRECEIVER }} --notionToken ${{ secrets.NOTIONTOKEN }} --mainDataBase ${{ secrets.MAINDATABASE }} 
        rm -rf ./Scripts/attachments/*
